// GENERATED by scripts/scan-audio.mjs — do not edit by hand.
// Regenerate with `npm run scan:audio` after adding or replacing a narration file.

export interface NarrationTrack {
  /** Path relative to the site root. */
  file: string;
  bytes: number;
  /** Playable length in seconds, measured from the MPEG frame headers. */
  duration: number;
}

export const narrationTracks: NarrationTrack[] = [
  { file: "assets/audio/u1-full.mp3", bytes: 4280961, duration: 177.97 },
  { file: "assets/audio/u1-n1.mp3", bytes: 4531130, duration: 188.4 },
  { file: "assets/audio/u1-n5.mp3", bytes: 3779432, duration: 157.07 },
  { file: "assets/audio/u2-a.mp3", bytes: 17672000, duration: 735.9 },
  { file: "assets/audio/u2-intro.mp3", bytes: 2259358, duration: 93.7 },
  { file: "assets/audio/u2-n5.mp3", bytes: 5400946, duration: 224.6 }
];

const byFile = new Map(narrationTracks.map((t) => [t.file, t]));

export function narrationTrack(file: string): NarrationTrack | undefined {
  return byFile.get(file);
}

/** A track is deliverable only if it exists and decodes to real audio. */
export function hasNarration(file: string, needUntil = 0): boolean {
  const t = byFile.get(file);
  if (!t || t.duration <= 0) return false;
  // Half a second of tolerance: the last frame often lands a hair short of the cut point.
  return t.duration >= needUntil - 0.5;
}
