// GENERATED by scripts/scan-video.mjs — do not edit by hand.
// Regenerate with `npm run scan:video` after rendering or replacing a nugget video.

export interface VideoTrack {
  /** Unit number as written in the content, e.g. "01". */
  unit: string;
  /** 1-based nugget number inside the unit. */
  n: number;
  /** Path relative to the site root. */
  file: string;
  bytes: number;
  /** Playable length in seconds, read from the MP4 movie header. */
  duration: number;
}

export const videoTracks: VideoTrack[] = [
  {
    "unit": "01",
    "n": 1,
    "file": "assets/video/u01-n01-v2.mp4",
    "bytes": 12733018,
    "duration": 159.53
  },
  {
    "unit": "01",
    "n": 2,
    "file": "assets/video/u01-n02-v2.mp4",
    "bytes": 12595863,
    "duration": 140.33
  },
  {
    "unit": "01",
    "n": 3,
    "file": "assets/video/u01-n03-v2.mp4",
    "bytes": 13539678,
    "duration": 174.55
  },
  {
    "unit": "01",
    "n": 4,
    "file": "assets/video/u01-n04-v2.mp4",
    "bytes": 13014963,
    "duration": 172.22
  },
  {
    "unit": "02",
    "n": 1,
    "file": "assets/video/u02-n01.mp4",
    "bytes": 29079829,
    "duration": 191.06
  },
  {
    "unit": "03",
    "n": 1,
    "file": "assets/video/u03-n01.mp4",
    "bytes": 10784337,
    "duration": 135.53
  },
  {
    "unit": "03",
    "n": 2,
    "file": "assets/video/u03-n02.mp4",
    "bytes": 9474503,
    "duration": 124.12
  }
];

const byKey = new Map(videoTracks.map((v) => [`${v.unit}/${v.n}`, v]));

/**
 * The rendered visualizer for a nugget, when there is one long enough to cover it.
 *
 * `needSeconds` is the segment's own length. A file shorter than that is a truncated
 * or partial render, and playing it would strand the learner before the narration
 * ends — so it is treated as absent and the nugget falls back to the CSS stage.
 */
export function videoTrack(unit: string, n: number, needSeconds: number): VideoTrack | undefined {
  const track = byKey.get(`${unit}/${n}`);
  if (!track || track.duration <= 0) return undefined;
  // The render carries a short end card past the narration, so it is always longer.
  return track.duration >= needSeconds - 0.5 ? track : undefined;
}
