// GENERATED by scripts/scan-video.mjs — do not edit by hand.
// Regenerate with `npm run scan:video` after rendering or replacing a nugget video.

export interface VideoTrack {
  /** Unit number as written in the content, e.g. "01". */
  unit: string;
  /** 1-based nugget number inside the unit. */
  n: number;
  /** Path relative to the site root. */
  file: string;
  bytes: number;
  /** Playable length in seconds, read from the MP4 movie header. */
  duration: number;
}

export const videoTracks: VideoTrack[] = [
  {
    "unit": "01",
    "n": 1,
    "file": "assets/video/u01-n01.mp4",
    "bytes": 25081263,
    "duration": 157.38
  },
  {
    "unit": "01",
    "n": 2,
    "file": "assets/video/u01-n02.mp4",
    "bytes": 23709007,
    "duration": 154.03
  },
  {
    "unit": "01",
    "n": 3,
    "file": "assets/video/u01-n03.mp4",
    "bytes": 21526924,
    "duration": 151.3
  },
  {
    "unit": "01",
    "n": 4,
    "file": "assets/video/u01-n04.mp4",
    "bytes": 22483791,
    "duration": 140.82
  },
  {
    "unit": "01",
    "n": 5,
    "file": "assets/video/u01-n05.mp4",
    "bytes": 24459140,
    "duration": 158.12
  }
];

const byKey = new Map(videoTracks.map((v) => [`${v.unit}/${v.n}`, v]));

/**
 * The rendered visualizer for a nugget, when there is one long enough to cover it.
 *
 * `needSeconds` is the segment's own length. A file shorter than that is a truncated
 * or partial render, and playing it would strand the learner before the narration
 * ends — so it is treated as absent and the nugget falls back to the CSS stage.
 */
export function videoTrack(unit: string, n: number, needSeconds: number): VideoTrack | undefined {
  const track = byKey.get(`${unit}/${n}`);
  if (!track || track.duration <= 0) return undefined;
  // The render carries a short end card past the narration, so it is always longer.
  return track.duration >= needSeconds - 0.5 ? track : undefined;
}
