#!/usr/bin/env node
/**
 * Scans public/assets/video and writes src/content/video-manifest.ts.
 *
 * The manifest is what the player reads to know whether a nugget has a rendered
 * visualizer to play instead of the CSS stage. Files are matched to segments by name
 * — u<unit>-n<nugget>.mp4, the same ids the Remotion compositions use — so producing
 * a nugget's video and running this script is all it takes to switch that nugget over.
 *
 * Durations come from the MP4 movie header rather than being trusted from anywhere
 * else: a truncated or placeholder file reports a length that will not match the
 * segment, and the player refuses it instead of putting the scrub bar in the wrong
 * place. The same lesson the audio scanner learned the hard way.
 *
 * NOT wired into prebuild, unlike the audio scanner. Once the renders live in a blob
 * store the local directory is empty, and a build-time scan would write an empty
 * manifest and silently drop every nugget back to the CSS stage. So the manifest is a
 * committed artifact: run this while the renders are still in public/assets/video,
 * commit the result, then upload and remove the files.
 *
 * As a second guard, it refuses to overwrite a populated manifest with an empty one.
 *
 * Run via `npm run scan:video`.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'public/assets/video';
const OUT = 'src/content/video-manifest.ts';

/** Walks the top-level boxes of an MP4 and reads the duration out of moov/mvhd. */
function readDuration(buf) {
  const boxes = (start, end) => {
    const found = [];
    let o = start;
    while (o + 8 <= end) {
      let size = buf.readUInt32BE(o);
      const type = buf.toString('latin1', o + 4, o + 8);
      let head = 8;
      if (size === 1) {
        size = Number(buf.readBigUInt64BE(o + 8));
        head = 16;
      }
      if (size === 0) size = end - o;
      if (size < head) break;
      found.push({ type, start: o + head, end: o + size });
      o += size;
    }
    return found;
  };

  const moov = boxes(0, buf.length).find((b) => b.type === 'moov');
  if (!moov) return 0;
  const mvhd = boxes(moov.start, moov.end).find((b) => b.type === 'mvhd');
  if (!mvhd) return 0;
  const version = buf.readUInt8(mvhd.start);
  // v1 widens the creation/modification times, pushing timescale and duration along.
  const at = version === 1 ? mvhd.start + 20 : mvhd.start + 12;
  const timescale = buf.readUInt32BE(at);
  const duration = version === 1 ? Number(buf.readBigUInt64BE(at + 4)) : buf.readUInt32BE(at + 4);
  return timescale > 0 ? Number((duration / timescale).toFixed(2)) : 0;
}

const tracks = [];
if (existsSync(DIR)) {
  for (const name of readdirSync(DIR).sort()) {
    const match = /^u(\d+)-n(\d+)\.mp4$/.exec(name);
    if (!match) {
      console.warn(`skipped ${name}: expected u<unit>-n<nugget>.mp4`);
      continue;
    }
    const path = join(DIR, name);
    const bytes = statSync(path).size;
    const duration = readDuration(readFileSync(path));
    tracks.push({ unit: match[1], n: Number(match[2]), file: `assets/video/${name}`, bytes, duration });
    console.log(`${name}  ${bytes} bytes  ${duration}s`);
  }
}

// Never let an empty scan clobber a manifest that lists real renders: that is the
// exact shape of the accident this script must not enable.
if (tracks.length === 0 && existsSync(OUT)) {
  const current = readFileSync(OUT, 'utf8');
  const populated = /"file":\s*"assets\/video\//.test(current);
  if (populated) {
    console.error(
      `No files in ${DIR}, but ${OUT} lists renders already.\n` +
        'Refusing to write an empty manifest — that would drop every nugget back to the\n' +
        'CSS stage. The renders now live in the blob store; the manifest is committed.\n' +
        'To rebuild it, restore the files to that directory first.',
    );
    process.exit(1);
  }
}

const body = `// GENERATED by scripts/scan-video.mjs — do not edit by hand.
// Regenerate with \`npm run scan:video\` after rendering or replacing a nugget video.

export interface VideoTrack {
  /** Unit number as written in the content, e.g. "01". */
  unit: string;
  /** 1-based nugget number inside the unit. */
  n: number;
  /** Path relative to the site root. */
  file: string;
  bytes: number;
  /** Playable length in seconds, read from the MP4 movie header. */
  duration: number;
}

export const videoTracks: VideoTrack[] = ${JSON.stringify(tracks, null, 2)};

const byKey = new Map(videoTracks.map((v) => [\`\${v.unit}/\${v.n}\`, v]));

/**
 * The rendered visualizer for a nugget, when there is one long enough to cover it.
 *
 * \`needSeconds\` is the segment's own length. A file shorter than that is a truncated
 * or partial render, and playing it would strand the learner before the narration
 * ends — so it is treated as absent and the nugget falls back to the CSS stage.
 */
export function videoTrack(unit: string, n: number, needSeconds: number): VideoTrack | undefined {
  const track = byKey.get(\`\${unit}/\${n}\`);
  if (!track || track.duration <= 0) return undefined;
  // The render carries a short end card past the narration, so it is always longer.
  return track.duration >= needSeconds - 0.5 ? track : undefined;
}
`;

writeFileSync(OUT, body);
console.log(`\n${tracks.length} video track(s) -> ${OUT}`);
