#!/usr/bin/env node
/**
 * Scans public/assets/audio and writes src/content/narration-manifest.ts.
 *
 * The manifest is what the player and the admin content-health panel read to know
 * whether a segment's narration is actually deliverable. Durations come from walking
 * the MPEG frame headers, so a truncated or placeholder file reports 0 and is treated
 * as missing rather than silently serving garbage to a learner.
 *
 * It also flags a stale Xing/Info header — a nugget cut out of a longer master keeps
 * the master's header unless the tool rewrites it, and browsers trust that header for
 * both `duration` and seeking. One such file shipped here claiming 431s of audio in a
 * 149s file, which put every scrub in the wrong place. Fix by stripping the header
 * frame (it carries no audio) or re-encoding, then run this again.
 *
 * Run via `npm run scan:audio` (also wired into prebuild).
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'public/assets/audio';
const OUT = 'src/content/narration-manifest.ts';

const BITRATES = [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 0];
const RATES = [44100, 48000, 32000];

/**
 * Walks every MPEG frame in the file.
 *
 * Returns the real duration (0 when no valid frame is found) and, when the first frame
 * carries a Xing/Info header, the duration that header claims — the two disagreeing is
 * the stale-header case described above.
 */
function probeMp3(buf) {
  let i = 0;
  if (buf.length > 10 && buf.subarray(0, 3).toString('latin1') === 'ID3') {
    const size = ((buf[6] & 0x7f) << 21) | ((buf[7] & 0x7f) << 14) | ((buf[8] & 0x7f) << 7) | (buf[9] & 0x7f);
    i = 10 + size;
  }
  let seconds = 0;
  let claimed = null;
  let first = true;
  while (i < buf.length - 4) {
    if (buf[i] !== 0xff || (buf[i + 1] & 0xe0) !== 0xe0) { i++; continue; }
    const version = (buf[i + 1] >> 3) & 3;
    const layer = (buf[i + 1] >> 1) & 3;
    const bitrate = BITRATES[(buf[i + 2] >> 4) & 15];
    const rateIndex = (buf[i + 2] >> 2) & 3;
    const padding = (buf[i + 2] >> 1) & 1;
    if (bitrate === 0 || rateIndex === 3 || layer !== 1) { i++; continue; }
    let rate = RATES[rateIndex];
    if (version === 2) rate /= 2;
    if (version === 0) rate /= 4;
    const samplesPerFrame = version === 3 ? 1152 : 576;
    const frameLength = Math.floor((samplesPerFrame / 8) * bitrate * 1000 / rate) + padding;
    if (frameLength < 4) { i++; continue; }

    if (first) {
      first = false;
      const frame = buf.subarray(i, i + frameLength);
      for (const tag of ['Xing', 'Info']) {
        const at = frame.indexOf(Buffer.from(tag));
        if (at < 0) continue;
        const flags = frame.readUInt32BE(at + 4);
        // Bit 0 of the flags means a frame count follows the flags word.
        if (flags & 1) claimed = (frame.readUInt32BE(at + 8) * samplesPerFrame) / rate;
        break;
      }
    }

    seconds += samplesPerFrame / rate;
    i += frameLength;
  }
  return { seconds, claimed };
}

const tracks = [];
const warnings = [];
for (const name of readdirSync(DIR).sort()) {
  if (!name.toLowerCase().endsWith('.mp3')) continue;
  const path = join(DIR, name);
  const bytes = statSync(path).size;
  const { seconds, claimed } = probeMp3(readFileSync(path));
  const duration = Math.round(seconds * 100) / 100;
  // A second of slack: the last frame often lands a hair short of a round number.
  if (claimed != null && Math.abs(claimed - seconds) > 1) {
    warnings.push(
      `${name}: Xing/Info header claims ${claimed.toFixed(2)}s but the file holds ${duration}s. ` +
        'Browsers trust that header for duration AND seeking, so scrubbing will land in the ' +
        'wrong place. Strip the header frame or re-encode, then run this again.',
    );
  }
  tracks.push({ file: `assets/audio/${name}`, bytes, duration });
}

const body = tracks
  .map((t) => `  { file: ${JSON.stringify(t.file)}, bytes: ${t.bytes}, duration: ${t.duration} }`)
  .join(',\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/scan-audio.mjs — do not edit by hand.
// Regenerate with \`npm run scan:audio\` after adding or replacing a narration file.

export interface NarrationTrack {
  /** Path relative to the site root. */
  file: string;
  bytes: number;
  /** Playable length in seconds, measured from the MPEG frame headers. */
  duration: number;
}

export const narrationTracks: NarrationTrack[] = [
${body}
];

const byFile = new Map(narrationTracks.map((t) => [t.file, t]));

export function narrationTrack(file: string): NarrationTrack | undefined {
  return byFile.get(file);
}

/** A track is deliverable only if it exists and decodes to real audio. */
export function hasNarration(file: string, needUntil = 0): boolean {
  const t = byFile.get(file);
  if (!t || t.duration <= 0) return false;
  // Half a second of tolerance: the last frame often lands a hair short of the cut point.
  return t.duration >= needUntil - 0.5;
}
`,
);

console.log(`${OUT}: ${tracks.length} tracks`);
for (const t of tracks) {
  console.log(`  ${t.file.padEnd(28)} ${String(t.bytes).padStart(9)} bytes  ${t.duration.toFixed(2)}s${t.duration <= 0 ? '  << UNPLAYABLE' : ''}`);
}
if (warnings.length) {
  console.warn('\nSTALE DURATION HEADER:');
  for (const w of warnings) console.warn(`  ! ${w}`);
  process.exitCode = 1;
}
