#!/usr/bin/env node
/**
 * Scans public/assets/audio and writes src/content/narration-manifest.ts.
 *
 * The manifest is what the player and the admin content-health panel read to know
 * whether a segment's narration is actually deliverable. Durations come from walking
 * the MPEG frame headers, so a truncated or placeholder file reports 0 and is treated
 * as missing rather than silently serving garbage to a learner.
 *
 * Run via `npm run scan:audio` (also wired into prebuild).
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'public/assets/audio';
const OUT = 'src/content/narration-manifest.ts';

const BITRATES = [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 0];
const RATES = [44100, 48000, 32000];

/** Sums frame durations across an MPEG audio file. Returns 0 if no valid frame is found. */
function mp3Duration(buf) {
  let i = 0;
  if (buf.length > 10 && buf.subarray(0, 3).toString('latin1') === 'ID3') {
    const size = ((buf[6] & 0x7f) << 21) | ((buf[7] & 0x7f) << 14) | ((buf[8] & 0x7f) << 7) | (buf[9] & 0x7f);
    i = 10 + size;
  }
  let seconds = 0;
  while (i < buf.length - 4) {
    if (buf[i] !== 0xff || (buf[i + 1] & 0xe0) !== 0xe0) { i++; continue; }
    const version = (buf[i + 1] >> 3) & 3;
    const layer = (buf[i + 1] >> 1) & 3;
    const bitrate = BITRATES[(buf[i + 2] >> 4) & 15];
    const rateIndex = (buf[i + 2] >> 2) & 3;
    const padding = (buf[i + 2] >> 1) & 1;
    if (bitrate === 0 || rateIndex === 3 || layer !== 1) { i++; continue; }
    let rate = RATES[rateIndex];
    if (version === 2) rate /= 2;
    if (version === 0) rate /= 4;
    const samplesPerFrame = version === 3 ? 1152 : 576;
    const frameLength = Math.floor((samplesPerFrame / 8) * bitrate * 1000 / rate) + padding;
    if (frameLength < 4) { i++; continue; }
    seconds += samplesPerFrame / rate;
    i += frameLength;
  }
  return seconds;
}

const tracks = [];
for (const name of readdirSync(DIR).sort()) {
  if (!name.toLowerCase().endsWith('.mp3')) continue;
  const path = join(DIR, name);
  const bytes = statSync(path).size;
  const duration = mp3Duration(readFileSync(path));
  tracks.push({ file: `assets/audio/${name}`, bytes, duration: Math.round(duration * 100) / 100 });
}

const body = tracks
  .map((t) => `  { file: ${JSON.stringify(t.file)}, bytes: ${t.bytes}, duration: ${t.duration} }`)
  .join(',\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/scan-audio.mjs — do not edit by hand.
// Regenerate with \`npm run scan:audio\` after adding or replacing a narration file.

export interface NarrationTrack {
  /** Path relative to the site root. */
  file: string;
  bytes: number;
  /** Playable length in seconds, measured from the MPEG frame headers. */
  duration: number;
}

export const narrationTracks: NarrationTrack[] = [
${body}
];

const byFile = new Map(narrationTracks.map((t) => [t.file, t]));

export function narrationTrack(file: string): NarrationTrack | undefined {
  return byFile.get(file);
}

/** A track is deliverable only if it exists and decodes to real audio. */
export function hasNarration(file: string, needUntil = 0): boolean {
  const t = byFile.get(file);
  if (!t || t.duration <= 0) return false;
  // Half a second of tolerance: the last frame often lands a hair short of the cut point.
  return t.duration >= needUntil - 0.5;
}
`,
);

console.log(`${OUT}: ${tracks.length} tracks`);
for (const t of tracks) {
  console.log(`  ${t.file.padEnd(28)} ${String(t.bytes).padStart(9)} bytes  ${t.duration.toFixed(2)}s${t.duration <= 0 ? '  << UNPLAYABLE' : ''}`);
}
